---
- name: Create the secret.willemsma.it/v1alpha1.SyncedSecret (tls)
  k8s:
    state: present
    namespace: '{{ namespace }}'
    definition: "{{ lookup('template', '/'.join([samples_dir, cr_file])) | from_yaml }}"
    wait: yes
    wait_timeout: 60
    wait_condition:
      type: Successful
      status: "True"
  loop:
    - secret_v1alpha1_syncedsecret_tls.yaml
  loop_control:
    loop_var: cr_file

- name: Fetch a list of secrets (tls)
  set_fact:
    tls: "{{ tls|default([]) + query('kubernetes.core.k8s', api_version='v1', kind='secret', resource_name=s.resource, namespace=s.namespace) }}"
  loop:
    - resource: synced-from-authorative-namespace-tls
      namespace: default
    - resource: synced-from-authorative-namespace-tls
      namespace: cust-a
    - resource: synced-from-authorative-namespace-tls
      namespace: dev
    - resource: synced-from-authorative-namespace-tls
      namespace: prd

  loop_control:
    loop_var: s
    
- debug: var=tls

- pause:
    seconds: 10
    prompt: Give operator time to sync secrets

- name: Test secrets exist in target
  assert:
    that: tls|length == expected_secrets
    fail_msg: "Expected {{ expected_secrets }} secrets to be synced to targets but found {{ tls|length }}"
  vars:
    expected_secrets: 4
