apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "secret.willemsma.it/v1alpha1",
          "kind": "SyncedSecret",
          "metadata": {
            "name": "syncedsecret-docker"
          },
          "spec": {
            "source": "authorative-namespace/docker",
            "targets": [
              "default/synced-from-authorative-namespace-docker",
              "cust-a/synced-from-authorative-namespace-docker",
              "dev/synced-from-authorative-namespace-docker"
            ]
          }
        },
        {
          "apiVersion": "secret.willemsma.it/v1alpha1",
          "kind": "SyncedSecret",
          "metadata": {
            "name": "syncedsecret-generic"
          },
          "spec": {
            "source": "authorative-namespace/hello",
            "targets": [
              "default/synced-from-authorative-namespace-hello",
              "cust-a/synced-from-authorative-namespace-hello",
              "dev/synced-from-authorative-namespace-hello",
              "prd/synced-from-authorative-namespace-hello"
            ]
          }
        },
        {
          "apiVersion": "secret.willemsma.it/v1alpha1",
          "kind": "SyncedSecret",
          "metadata": {
            "name": "syncedsecret-tls"
          },
          "spec": {
            "source": "authorative-namespace/tls",
            "targets": [
              "default/synced-from-authorative-namespace-tls",
              "cust-a/synced-from-authorative-namespace-tls",
              "dev/synced-from-authorative-namespace-tls",
              "prd/synced-from-authorative-namespace-tls"
            ]
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.15.0+git
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
  name: synced-secret-operator.v0.0.2
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: SyncedSecret
      name: syncedsecrets.secret.willemsma.it
      version: v1alpha1
  description: Synced Secret Operator description. TODO.
  displayName: Synced Secret Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        - apiGroups:
          - ""
          resources:
          - secrets
          - pods
          - pods/exec
          - pods/log
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - list
        - apiGroups:
          - secret.willemsma.it
          resources:
          - syncedsecrets
          - syncedsecrets/status
          - syncedsecrets/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: controller-manager
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          - pods
          - pods/exec
          - pods/log
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - list
        - apiGroups:
          - secret.willemsma.it
          resources:
          - syncedsecrets
          - syncedsecrets/status
          - syncedsecrets/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: synced-secret-operator-controller-manager
      deployments:
      - name: controller-manager
        spec:
          selector: null
          strategy: {}
          template:
            metadata: {}
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources: {}
              - args:
                - --health-probe-bind-address=:6789
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                - --leader-election-id=synced-secret-operator
                name: manager
                resources: {}
      - name: controller-manager
        spec:
          selector: null
          strategy: {}
          template:
            metadata: {}
            spec:
              containers:
              - args:
                - --config=controller_manager_config.yaml
                name: manager
                resources: {}
                volumeMounts:
                - mountPath: /controller_manager_config.yaml
                  name: manager-config
                  subPath: controller_manager_config.yaml
              volumes:
              - configMap:
                  name: manager-config
                name: manager-config
      - name: controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --leader-elect
                - --leader-election-id=synced-secret-operator
                env:
                - name: ANSIBLE_GATHERING
                  value: explicit
                image: controller:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 6789
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 6789
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 768Mi
                  requests:
                    cpu: 10m
                    memory: 256Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: controller-manager
              terminationGracePeriodSeconds: 10
      - name: synced-secret-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources: {}
              - args:
                - --health-probe-bind-address=:6789
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                - --leader-election-id=synced-secret-operator
                env:
                - name: ANSIBLE_GATHERING
                  value: explicit
                image: mwillemsma/synced-secrets-operator:0.0.2
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 6789
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 6789
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 768Mi
                  requests:
                    cpu: 10m
                    memory: 256Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: synced-secret-operator-controller-manager
              terminationGracePeriodSeconds: 10
      - name: controller-manager
        spec:
          selector: null
          strategy: {}
          template:
            metadata: {}
            spec:
              containers:
              - env:
                - name: ANSIBLE_DEBUG_LOGS
                  value: "TRUE"
                name: manager
                resources: {}
      - name: controller-manager
        spec:
          selector: null
          strategy: {}
          template:
            metadata: {}
            spec:
              containers:
              - image: testing
                name: manager
                resources: {}
      - name: controller-manager
        spec:
          selector: null
          strategy: {}
          template:
            metadata: {}
            spec:
              containers:
              - imagePullPolicy: Always
                name: manager
                resources: {}
      - name: controller-manager
        spec:
          selector: null
          strategy: {}
          template:
            metadata: {}
            spec:
              containers:
              - imagePullPolicy: IfNotPresent
                name: manager
                resources: {}
      - name: controller-manager
        spec:
          selector: null
          strategy: {}
          template:
            metadata: {}
            spec:
              containers:
              - imagePullPolicy: Never
                name: manager
                resources: {}
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: controller-manager
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: synced-secret-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - synced-secret-operator
  links:
  - name: Synced Secret Operator
    url: https://synced-secret-operator.domain
  maintainers:
  - email: martin@willemsma.it
    name: Martin Willemsma
  maturity: alpha
  provider:
    name: Provider Name
    url: https://willemsma.it
  version: 0.0.2
