apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: syncedsecret-viewer-role
rules:
- apiGroups:
  - secret.willemsma.it
  resources:
  - syncedsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secret.willemsma.it
  resources:
  - syncedsecrets/status
  verbs:
  - get
