---
apiVersion: secret.willemsma.it/v1alpha1
kind: SyncedSecret
metadata:
  name: syncedsecret-tls
  # annotations:
    # ansible.operator-sdk/reconcile-period: "30s"
spec:
  source: authorative-namespace/tls
  targets:
    - default/synced-from-authorative-namespace-tls
    - cust-a/synced-from-authorative-namespace-tls
    - dev/synced-from-authorative-namespace-tls
    - prd/synced-from-authorative-namespace-tls
