---
apiVersion: secret.willemsma.it/v1alpha1
kind: SyncedSecret
metadata:
  name: syncedsecret-generic
  # annotations:
    # ansible.operator-sdk/reconcile-period: "30s"
spec:
  source: authorative-namespace/hello
  targets:
    - default/synced-from-authorative-namespace-hello
    - cust-a/synced-from-authorative-namespace-hello
    - dev/synced-from-authorative-namespace-hello
    - prd/synced-from-authorative-namespace-hello


