---
apiVersion: secret.willemsma.it/v1alpha1
kind: SyncedSecret
metadata:
  name: syncedsecret-docker
  # annotations:
    # ansible.operator-sdk/reconcile-period: "30s"
spec:
  source: authorative-namespace/docker
  targets:
    - default/synced-from-authorative-namespace-docker
    - cust-a/synced-from-authorative-namespace-docker
    - dev/synced-from-authorative-namespace-docker
