---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: syncedsecrets.secret.willemsma.it
spec:
  group: secret.willemsma.it
  names:
    kind: SyncedSecret
    listKind: SyncedSecretList
    plural: syncedsecrets
    singular: syncedsecret
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: SyncedSecret is the Schema for the syncedsecrets API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of SyncedSecret
            type: object
            # x-kubernetes-preserve-unknown-fields: true
            required: ["source","targets"]
            properties:
              source:
                type: string
                description: 'The source secret that should be synced to target secrets'
              targets:
                type: array
                description: 'The list of targets the source secret will be synced to'
                items:
                  type: string
              target_state:
                type: string
                description: 'Control the desired state of the target secrets'
              no_log:
                type: boolean
                description: 'Hide the operator output in manager logs'
          status:
            description: Status defines the observed state of SyncedSecret
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
